### ISSUE TITLE
`HOMEBREW_PREFIX already set, exiting` after upgrading to v0.2.0

### ISSUE THREAD

**Issue by amitkot** [eugenesvk/xontrib-homebrew#1]
After upgrading to v0.2.0 I get this error every time I run `xontrib load homebrew`:

```
xontrib-Homebrew: HOMEBREW_PREFIX already set, exiting
```

When switching back to v0.1.0 it works fine again:
```
xpip install xontrib-homebrew==0.1.0
```

My `.xonshrc` contains a bunch of other things but only one call to `xontrib load homebrew` and I do not define this env variable manually in it.

**Comment by eugenesvk** [comment]
Version 0.2.0 autoloads itself, so you your'e loading it the second time manually `xontrib load homebrew` and thus getting the log message (though this is not an error message, it's a log message)
Also, it should only appear if you have manually set `$XONTRIB_HOMEBREW_LOGLEVEL` to a higher level  (`3 print more verbose messages`, while the default is `1`), can you check that and set it to something less verbose?

Otherwise it's not a big deal to load it twice, the xontrib does nothing and just exists

**Comment by ghost** [comment]
@eugenesvk yes I did have the `$XONTRIB_HOMEBREW_LOGLEVEL` flag on - I added it previously when trying to debug some issue.

I tested again and figured out the problem. I noticed that I set the `$PATH` manually with all of the values I wanted.
I guess this xontrib loads automatically first, before my `.xonshrc` is run, right?
I changed my `.xonshrc` to prepend instead and now it gives a similar result to what I used to have with 0.1.0.
Thanks!

**Comment by eugenesvk** [comment]
> I guess this xontrib loads automatically first, before my .xonshrc is run, right?

Most likely, and it might actually be an issue as  autoloading ignores your environment variables, so I've made a separate branch that disables it, check out 
https://github.com/eugenesvk/xontrib-homebrew#known-issues for how to install it if you encounter such issues (and maybe upvote the xonsh bug report linked there)

Anyway, given that there are two solutions:
- disable the log verbosity
- install the non-auto-loaded alternative

think this issue is resolved

**Comment by amitkot** [comment]
Great, thanks @eugenesvk 🙏
